### ISSUE TITLE
Can you please updated for Ti. SDK 5.2.0GA+

### ISSUE THREAD

**Issue by implicitli** [ricardoalcocer/actionbarextras#103]
Can you please updated for Ti. SDK 5.2.0GA+

**Comment by manumaticx** [comment]
What's the issue with 5.2.0 you are facing?

**Comment by manumaticx** [comment]
@sitegrafx ABX runs fine on 5.2.2.GA - if you see any problem, please let me know.

**Comment by sitegrafx** [comment]
If I try to use AppC GUI (tiapp.xml) it shows not show the module.  

So I manually added the lines to the tiapp.xml file:
<module platform="android">com.alcoapps.actionbarextras</module>

Then when I go back to tiapp.xml (GUI view) the module shows up with a yellow exclamation and hovering reveals this text:
The module "com.alcoapps.actionbarextras" module is not supported by Titanium SDK 5.2.0GA

**Comment by manumaticx** [comment]
@sitegrafx I have to admit that I haven't used Appc Studio for a long time. But I have just created a new test project in Studio, selected SDK 5.2.2.GA and added the actionbarextras module (1.6.9) from global installation. I was able to run the project without any error.

Which version of the module are you using? I need more information on how to reproduce this. I have actually never seen this error and I cannot imagine why it could be thrown.

**Comment by ipep84** [comment]
I Think your are trying to run https://github.com/manumaticx/NavigationDrawer-Demo , when you import the app demo shows the error, forget the error, go to Ti.app file and delete the references to ABX, download the last versión of ABX  and works like a charm .
