### ISSUE TITLE
Not supported by Titanium 5.5.1

### ISSUE THREAD

**Issue by deckameron** [ricardoalcocer/actionbarextras#114]
Hi Ricardo,

I am using 1.7.1 and I have tried Titanium SDK 5.5.1 and 6.0.0 but I couldn't get it to work. What am I doing wrong? :-)

![Not supported](http://i.imgur.com/3FLfc3y.png)

**Comment by HazemKhaled** [comment]
Use version 1.6.9 with 5.5.1, 1.7.x require Titanium SDK 6+

**Comment by deckameron** [comment]
Thanks @HazemKhaled !
