### ISSUE TITLE
SetUpColor always set an "back arrow" icon

### ISSUE THREAD

**Issue by chmiiller** [ricardoalcocer/actionbarextras#118]
Hi there,
the method `handleSetUpColor` always set the left icon as an "back arrow" and then changes its color. The best behavior would be to simple get the current icon and change its color instead of adding an arrow every time.
I'm using abx along a drawer module and when I want to color the burger button, it gets changed to an arrow, which is not useful for final users.
Do you know how to fix it?

Thanks!

**Comment by manumaticx** [comment]
Seems, that doesn't work with Android Support Library version 23.2.x anymore. Will fix it asap. (note to myself: https://stackoverflow.com/questions/35632576/error-cannot-find-symbol-variable-abc-ic-ab-back-mtrl-am-alpha)

**Comment by manumaticx** [comment]
Let me know if this works (I admit, I didn't test, just used this solution from SO 🙈 )
