### ISSUE TITLE
no method 'setHomeAsUpIcon'

### ISSUE THREAD

**Issue by dave-lee-hk** [ricardoalcocer/actionbarextras#57]
Hi, I just discovered this module and trying to add it to my project. However I got the following error. Even in the example App. Any fix?

~~~
[ERROR] :  TiExceptionHandler: (main) [0,103866] - Message: Uncaught TypeError: Object #<Actionbarextras> has no method 'setHomeAsUpIcon'
[ERROR] :  TiExceptionHandler: (main) [0,103866] - Source:                 abx.setHomeAsUpIcon("/images/menu.png");
[ERROR] :  V8Exception: Exception occurred at app.js:58: Uncaught TypeError: Object #<Actionbarextras> has no method 'setHomeAsUpIcon'
~~~

By the way, I would like to use the same module to add a star icon for bookmarking, and hopefully could toggle the star icon color. Is it possible?

Thanks.

**Comment by manumaticx** [comment]
@dave-lee-hk 
setHomeAsUpIcon was added in version 1.3.8
Wich version have you used?

Toggling menu icons can be done without this module. Just use the [setIcon](http://docs.appcelerator.com/titanium/latest/#!/api/Titanium.Android.MenuItem-method-setIcon)-method to do this.

**Comment by dave-lee-hk** [comment]
I happened to be 0.0.1 less (1.3.7) , should be latest by my reporting time. Will try the latest and follow the other pointer.

Thanks for the help :)
