### ISSUE TITLE
Question: Magnifier icon in the SearchView text field

### ISSUE THREAD

**Issue by Claymm** [ricardoalcocer/actionbarextras#61]
Is it possible to change this icon?
Also I've tried using another image for the cancel icon but it was stretched and came over the default icon so I could see both. One on top of each other.

**Comment by manumaticx** [comment]
Hi @Claymm 
I know, there's currently an issue with changing the cancel icon, I still need to find a fix for this. Same for the magnifier icon. I hope I can come up with a solution very soon.

**Comment by Claymm** [comment]
Ok cool no worries. Keep up the good work!

**Comment by Claymm** [comment]
You rock! Thanks pal!

**Comment by manumaticx** [comment]
:v:
