### ISSUE TITLE
Add an option to set StatusBarColor for Android 5/MaterialDesign

### ISSUE THREAD

**Issue by janisr** [ricardoalcocer/actionbarextras#71]
Maybe something like in here??

http://stackoverflow.com/questions/27093287/how-to-change-status-bar-color-to-match-app-in-lollipop-android

**Comment by manumaticx** [comment]
Yep, I've seen this. This should definitely be possible with ABX although I'd always encourage to use Themes for styling these colors. But you're right, it should also be possible to change at runtime.

**Comment by janisr** [comment]
Implemented in #73

**Comment by manumaticx** [comment]
Just thought that it would be nice if this method would automatically set the statusbar color according to the actionbar color if you do not pass any color. Does that make sense?

**Comment by janisr** [comment]
That would be nice. Actually taking a step further it would be nice to merge those methods - when setting ActionBar color it calculates StatusBar color with the offset specified by design guidelines and sets that.

**Comment by manumaticx** [comment]
I really like this idea. Would be very handy
