### ISSUE TITLE
Dropdown preset?

### ISSUE THREAD

**Issue by AppWerft** [ricardoalcocer/actionbarextras#74]
Hi Manu + Ricardo,

it it possible to preset the list?

Codestrong!

Rainer

**Comment by manumaticx** [comment]
@AppWerft what do you mean by preset?

**Comment by AppWerft** [comment]
I have a list of countries and I want pfreset to 'Germany' …

**Comment by manumaticx** [comment]
You can do this:

```js
abx.createDropdown({
  titles : ["USA", "UK", "Germany", "France"],
  index: 2
});
```

**Comment by AppWerft** [comment]
Thanx, this solved my problem.

Rainer

Am 03/06/15 um 16:18 schrieb Manuel Lehner:
>
> You can do this:
>
> abx.createDropdown({
>    titles:  ["USA","UK","Germany","France"],
>    index:  2
> });
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ricardoalcocer/actionbarextras/issues/74#issuecomment-108447490>.
>

-- 
*Dipl.-Ing. Rainer Schleevoigt*
Certified TYPO3 Integrator
Certified Titanium App Developer

	Novalisweg 10
22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||
