### ISSUE TITLE
Search in actionbar – how can I disable?

### ISSUE THREAD

**Issue by AppWerft** [ricardoalcocer/actionbarextras#75]
Hi,
~~~
var searchView = Ti.UI.Android.createSearchView({
    hintText : "Suche in Mediathek"
});
searchView.addEventListener('submit', function(_e) {
    require('ui/search.window')(.open();
    _e.source.blur(); <== I want to close (decollapse?) the searchview
});
~~~

~~~
АктйонБар.setSearchView({
                searchView : searchView,
                cancelIcon : "/images/cancel.png",
                searchIcon : "/images/search.png"
  });
~~~
How can I hide the input field in actionbar after submitting?

**Comment by manumaticx** [comment]
@AppWerft see [MenuItem.collapseActionView](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Android.MenuItem-method-collapseActionView)

```js
onCreateOptionsMenu = function(e) {

  var searchView = Ti.UI.Android.createSearchView({
    hintText : "Suche in Mediathek"
  });
  
  // you need to keep a reference to the menu item
  var searchMenu = e.menu.add({
    title: L('search'),
    icon: "/images/ic_menu_search.png",
    actionView: searchView,
    showAsAction : Ti.Android.SHOW_AS_ACTION_ALWAYS | Ti.Android.SHOW_AS_ACTION_COLLAPSE_ACTION_VIEW
  });

  searchView.addEventListener('submit', function(_e) {
    require('ui/search.window')(.open();
    searchMenu.collapseActionView(); // <-- this is how you do it :)
  });
 
};
```

**Comment by AppWerft** [comment]
Thanx, it works!

Am 11/06/15 um 11:37 schrieb Manuel Lehner:
>
> @AppWerft <https://github.com/AppWerft> see 
> MenuItem.collapseActionView 
> <http://docs.appcelerator.com/platform/latest/#%21/api/Titanium.Android.MenuItem-method-collapseActionView>
>
> onCreateOptionsMenu  =  function(e) {
>
>    var  searchView=  Ti.UI.Android.createSearchView({
>      hintText:  "Suche in Mediathek"
>    });
>
>    // you need to keep a reference to the menu item
>    var  searchMenu=  e.menu.add({
>      title:  L('search'),
>      icon:  "/images/ic_menu_search.png",
>      actionView:  searchView,
>      showAsAction:  Ti.Android.SHOW_AS_ACTION_ALWAYS | Ti.Android.SHOW_AS_ACTION_COLLAPSE_ACTION_VIEW
>    });
>
>    searchView.addEventListener('submit',function(_e) {
>      require('ui/search.window')(.open();
>      searchMenu.collapseActionView();// <-- this is how you do it :)
>    });
>
> };
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ricardoalcocer/actionbarextras/issues/75#issuecomment-111066083>.
>

-- 
*Dipl.-Ing. Rainer Schleevoigt*
Certified TYPO3 Integrator
Certified Titanium App Developer

	Novalisweg 10
22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||

**Comment by manumaticx** [comment]
(y)
