### ISSUE TITLE
Support Badge on MenuItem

### ISSUE THREAD

**Issue by xTear** [ricardoalcocer/actionbarextras#80]
Is it possible to support the badges on the Menuitem?

**Comment by manumaticx** [comment]
@xTear What badges do you mean?

**Comment by xTear** [comment]
@manumaticx  Yes i mean this badges.

**Comment by manumaticx** [comment]
@xTear Sorry, I don't think we'll add this here as this module is intended to support native features that are not exposed to the Titanium SDK. These badges are no native functionality. I've not seen this as part of any of Google's guidelines.
