### ISSUE TITLE
TabGroup Elevation

### ISSUE THREAD

**Issue by xTear** [ricardoalcocer/actionbarextras#81]
There is no elevation if you use a TabGroup

**Comment by manumaticx** [comment]
I think you need to set the `elevation` to both, actionbar _and_ tabgroup.

**Comment by xTear** [comment]
![bildschirmfoto 2015-07-30 um 13 34 44](https://cloud.githubusercontent.com/assets/6847876/8982265/d3db803e-36bf-11e5-887e-f7a0d6410289.png)

**Comment by manumaticx** [comment]
Hm, I've just tested this. strangely enough it works in landscape mode. I don't think this is default Android behavior. It might be a Titanium issue. But I don't see any chance how this could be fixed here in the abx module.
