### ISSUE TITLE
Animated Material Icons

### ISSUE THREAD

**Issue by Brian-McBride** [ricardoalcocer/actionbarextras#85]
It would be great to enable this as a possible addition to the lib:

https://github.com/balysv/material-menu

The biggest hindrance is that when Titanium properly supports the new AppCompat libs and moves to the arguably better ToolBar widget, this module would break.

**Comment by manumaticx** [comment]
The lib seems to support toolbar too, so that shouldn't be a problem.

I just need to think about how this could work together with DrawerLayout.... but theoretically it should be absolutely possible. I'll have a look as soon as I have some time

**Comment by Anatidae-Project** [comment]
Speaking of drawer layout, I use this in my native Android apps:
https://github.com/mikepenz/MaterialDrawer

Mike has done an incredible job of making a super great drawer library. If someone wanted to wrap this as a module, it would be super. Alas, I don't have the time myself :(   Perhaps the link will inspire someone though.

**Comment by chmiiller** [comment]
omg @Brian-McBride that's awesome! Seems to be impossible do this with Titanium =/

**Comment by manumaticx** [comment]
@Brian-McBride I think I'm not going to implement this because:
- the lib is old (seems not up-to-date)
- trying to avoid another 3rd-party dependency
- it's a very special use-case
