### ISSUE TITLE
Can I replace the arrow icon in actionbar with another image icon with this module?

### ISSUE THREAD

**Issue by myselfdeveloping** [ricardoalcocer/actionbarextras#93]
I'm trying to change the arrow icon in action bar with another icon but I don't found a solution! Someone can help me?

**Comment by manumaticx** [comment]
Yes, it's all in the docs / example

```js
activity.onCreateOptionsMenu = function(e){
  activity.actionBar.displayHomeAsUp = true;
  abx.setHomeAsUpIcon("/images/myArrow.png");
};
```

**Comment by myselfdeveloping** [comment]
Doesn't work for me! This is my code:
var abx = require('com.alcoapps.actionbarextras');

// NOTE: make sure that your window is open 
// before you access the actionbar with abx
$.index.addEventListener('open',function(e){
  abx.title = "Valuta Amici";
  abx.titleColor = "White";
  abx.backgroundColor = "#017695";
  abx.displayHomeAsUp = true;
  abx.setHomeAsUpIcon("/images/icone/chiudi.png");
});

Where I'm wrong?

**Comment by manumaticx** [comment]
Try calling `activity.invalidateOptionsMenu();` after defining `onCreateOptionsMenu`:

```js
$.index.addEventListener('open',function(e){
	
   var activity = $.index.getActivity();
   
   if (activity) { 
        
        var abx = require('com.alcoapps.actionbarextras');
	   	abx.title = "Valuta Amici";
		abx.titleColor = "White";
		abx.backgroundColor = "#017695";
	 
	 activity.onCreateOptionsMenu = function(e){
  			activity.actionBar.displayHomeAsUp = true;
  			abx.setHomeAsUpIcon("/images/icone/cerca.png");
	};

        activity.invalidateOptionsMenu();
   	
   	
   	}
  
});
```

**Comment by manumaticx** [comment]
Ooops, this was wrong! :see_no_evil:

If it says `"Couldn't resolve /images/icone/cerca.png"` then you have to provide density-independent graphics (mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi), see #68

**Comment by myselfdeveloping** [comment]
Thanks a lot!

**Comment by manumaticx** [comment]
You're welcome :)
