### ISSUE TITLE
Delay of rendering

### ISSUE THREAD

**Issue by AppWerft** [ricardoalcocer/actionbarextras#94]
Hi Manu, hi Ricardo,
if I start the actionbarextra logic after openening of window then I see shortly the standard actionbar and ofter a couple of time the rendering of your module (+ subtitle,+ other font).

What can I do to avoid this. Or is it a mistake by me?

**Comment by manumaticx** [comment]
Not your fault. This is a Titanium limitation. See #91

**Comment by AppWerft** [comment]
Yes I see it. I have changed the ordering of code.
