### ISSUE TITLE
setStatusbarColor()

### ISSUE THREAD

**Issue by AppWerft** [ricardoalcocer/actionbarextras#96]
only works on newest Android?
compiled with 5.1.0.GA I see the colored bar only on my NEXUS5, other smartphones shows white on black (CAT,NEXUS7, NEXUS9,OnePlus)

**Comment by manumaticx** [comment]
It should work for Lollipop (5.0) and higher. But as this should be compatible with AppCompat, we might can remove this check. I'll test this soon.

**Comment by AppWerft** [comment]
Under <5 the bar color keeps  black.

**Comment by manumaticx** [comment]
It's because of [this if-clause](https://github.com/ricardoalcocer/actionbarextras/blob/master/src/com/alcoapps/actionbarextras/ActionbarextrasModule.java#L338) - probably because it crashes on Version <5

**Comment by manumaticx** [comment]
`setStatusBarColor` was added in API 21 (Lollipop) so this Check is legit
