### ISSUE TITLE
Adjust left padding of the ActionBar logo?

### ISSUE THREAD

**Issue by skypanther** [ricardoalcocer/actionbarextras#97]
Is there a way to adjust the padding to the left of the logo? The actual graphic is cropped very close to the left edge of its content. So the issue seems to be placement within the actionbar. Maybe this can be tweaked in the theme?

![screen shot 2016-01-07 at 11 42 38 am](https://cloud.githubusercontent.com/assets/507996/12176122/e0f867d0-b533-11e5-81e2-50d0c3b09718.png)

Created with 

```javascript
$.tabGroup.addEventListener("open", function () {
	var activity = $.tabGroup.getActivity();
	var actionBar = activity.getActionBar();
	var abx = require('com.alcoapps.actionbarextras');
	if (actionBar) {
		actionBar.setHomeButtonEnabled(true);
		abx.setDisplayShowHomeEnabled(true);
		abx.setDisplayUseLogoEnabled(true);
		actionBar.setIcon('/images/acv-white.png');
		abx.setDisplayShowTitleEnabled(false);
	}
...
```

**Comment by skypanther** [comment]
Never mind. I didn't realize I was still setting the logo in the Alloy `<ActionBar>` tag. Apparently, having both there caused the shift, or maybe that one overrode the one set in code. Whatever. Removing that tag, which I didn't need, has solved the issue.

**Comment by skypanther** [comment]
OK, I'm reopening this as I'm still seeing it. I'm not sure what I was thinking earlier. Turns out, the logo is centered. In our app, the logos moves as you switch tabs and the number of buttons on the right changes. 

I have tried with both `setIcon()` and `setLogo()` and get the same result. I've tried various theme modifications to left-align the logo. So far, I haven't hit the magic combination (if there is one).

**Comment by manumaticx** [comment]
@skypanther I'm investigating.
It seems it depends on the image you're using. I've tested two PNGs with the same code, please compare the results:

![appicon](https://cloud.githubusercontent.com/assets/2563642/12195772/09a9d3dc-b5fa-11e5-9549-9fcd3ea3e6b2.png)

```js
abx.setDisplayShowHomeEnabled(true);
activity.actionBar.setIcon('appicon.png');
abx.setDisplayShowTitleEnabled(false);
```
![screenshot_20160108-111641 2 png](https://cloud.githubusercontent.com/assets/2563642/12195757/d68caeac-b5f9-11e5-8a7a-456d013937df.jpg)

![appc-logo](https://cloud.githubusercontent.com/assets/2563642/12195769/03420e9c-b5fa-11e5-8a61-7d709d0d0e45.png)

```js
abx.setDisplayShowHomeEnabled(true);
activity.actionBar.setIcon('appicon.png');
abx.setDisplayShowTitleEnabled(false);
```
![screenshot_20160108-111800 2 png](https://cloud.githubusercontent.com/assets/2563642/12195763/e5742238-b5f9-11e5-9b43-f32b8e6629c9.jpg)

By the way, `setLogo` looks exact same. I was also testing some other images with the same effect. Looking into the Titanium source code, I tried to find out why the `setIcon` / `setLogo` are treating these images in different ways.

At first I thought that the [loadDrawable](https://github.com/appcelerator/titanium_mobile/blob/master/android/titanium/src/java/org/appcelerator/titanium/util/TiFileHelper.java#L308) method maybe treats the image like 9-patch in a weird way. But that would not make sense, right? I didn't debug it in detail so I'm not sure how exactly the file is loaded but somewhere the ImageView bounds are extended (1032 x 240) as you can see in the layout debugger:
![screenshot_20160108-113749-2](https://cloud.githubusercontent.com/assets/2563642/12196235/6aa08fb6-b5fd-11e5-826a-beedba2b19cb.png)

Still not sure if this is a Titanium issue or just normal Android behavior. This needs some further inspection. I'll let you know.

**Comment by artworker** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

artworker@naver.com 님께 보내신 메일 <Re: [actionbarextras] Adjust left padding of the ActionBar logo? (#97)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by skypanther** [comment]
Aha, that's it. The difference is whether you have a square or rectangular image. Mine is rectangular, as is the Appcelerator-and-triangle image. The Titanium icon is square. I expanded my logo to be square and now it's shown at the left of the ActionBar, though tiny.
![screen shot 2016-01-08 at 8 36 31 am](https://cloud.githubusercontent.com/assets/507996/12199055/3039e968-b5e3-11e5-9206-9f500972eb94.png)

I'm not sure if that's Android's handling of images or Titanium's. It would be nice to be able to override this so that a rectangular image could be left-aligned.

**Comment by manumaticx** [comment]
Well, this is strange. I've just checked another app where I'm using `actionBar.setLogo('/images/logo.png');` with a rectangular image but it's working fine here. Same device, same build target, same Appc Sdk.

![screenshot_20160108-154904 2 png](https://cloud.githubusercontent.com/assets/2563642/12200598/1c746ccc-b620-11e5-826c-4d7554249d20.jpg)
![screenshot_20160108-155025 2 png](https://cloud.githubusercontent.com/assets/2563642/12200599/1c78fc2e-b620-11e5-9804-a208c11baabb.jpg)

Not sure if this is the reason, but the only difference I see is that I'm using densitiy-specific images for this logo.

**Comment by skypanther** [comment]
I have density specific versions but perhaps they were the wrong size? Can you share the m/h/x/xx/xxx sizes you used so I can try?

**Comment by manumaticx** [comment]
I use this sizes
```
res-mdpi:    120 x 48
res-hdpi:    180 x 72
res-xhdpi:   240 x 96
res-xxhdpi:  360 x 144
res-xxxhdpi: 480 x 192
```

**Comment by skypanther** [comment]
Those sizes did it! Actually, it's the height that matters. My aspect ratio is a bit different. But I resized it to the corresponding heights in your list above. The logo is now left aligned.

![screen shot 2016-01-08 at 11 28 03 am](https://cloud.githubusercontent.com/assets/507996/12203075/171c2708-b5fb-11e5-8697-4887fa7595f4.png)

Since size matters, maybe this should be noted in the documentation for `setIcon()` and `setLogo()`? When I get a chance, I'll put in a PR.

**Comment by manumaticx** [comment]
Okay, this is something I also didn't know. I got these image sizes from the android design guide. So we still don't why the bounds get extended with a wrong size but as a rule of thumb you'd say that an actionbar logo must be 48 dp height. That actually makes sense since all Menu Icons also have a size of 48dp. Thanks for this clarification.
