### ISSUE TITLE
ABE causing app to crash on launch on Android 6 device

### ISSUE THREAD

**Issue by skypanther** [ricardoalcocer/actionbarextras#98]
On launch, our app crashes with the following in the logs. I am building with Ti SDK 5.1.2.GA and attempting to run on a Nexus 5x with Android 6.0.1.

```shell
E linker  : /data/app/com.myapp.demo-1/lib/arm/libcom.alcoapps.actionbarextras.so: has text relocations
E AndroidRuntime: FATAL EXCEPTION: KrollRuntimeThread
E AndroidRuntime: Process: com.myapp.demo, PID: 8429
E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.myapp.demo-1/lib/arm/libcom.alcoapps.actionbarextras.so: has text relocations
E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
E AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
E AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
E AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
E AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)
W ActivityManager:   Force finishing activity com.myapp.demo/.DemoActivity
```

[Edit: I removed the bit about compile problems because it turned out I had a typo in my Android SDK path in build.properties]

**Comment by manumaticx** [comment]
Hi Tim,

this is strange, I don't get such an error on my Nexus 5 with Android 6.0.1 tested with the [example](https://github.com/ricardoalcocer/actionbarextras/tree/master/example) and actionbarextras 1.6.8

I just have tried building from source with Appc SDK 5.1.2.GA (just by running `grunt`) which works fine here (BUILD SUCCESSFUL).

You might also need to update the [`.classpath`](https://github.com/ricardoalcocer/actionbarextras/blob/master/.classpath) to include the correct libs to the build path.

**Comment by skypanther** [comment]
Using the new version I provided in my PR, my app still crashes but on a different module which I've yet to update. Maybe it's just coincidence that this recompile looks like it resolved the issue.
